title: Prosodic Features' Criterion (PFC)
description: A new way to determine whether a speech-related feature carries prosodic information
show_downloads: false
google_analytics: true
theme: jekyll-theme-leap-day
